// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.rudtyz.grpcserver.dto;

public interface SampleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.SampleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();
}
